


 ***********************************************2/6/2020 1:13:22 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:13:22 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:14:23 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:14:23 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:18:53 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:18:53 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:18:58 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:18:58 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:19:38 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:19:38 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:20:34 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:20:34 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:20:53 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:20:53 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:21:55 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:21:55 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:39:11 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:39:11 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:39:14 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:39:14 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:39:15 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:39:15 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:39:20 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:39:20 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 1:41:31 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 1:41:31 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************2/6/2020 9:01:17 AM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser (ExchengeFoodAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	2/6/2020 9:01:17 AM


Source Exception               ====> 	   at ExchengeFoodAPI.Controllers.SecurityLoginController.GetInfoUser() in C:\Users\Sadek\source\repos\ExchengeFoodAPI\ExchengeFoodAPI\Controllers\SecurityLoginController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


